blank_issues_enabled: true
contact_links:
  - name: ðŸ“˜ Documentation
    url: https://github.com/minesa-org/mini-interaction/wiki
    about: Check the official wiki for setup and API reference
  - name: ðŸ’¬ Discussions
    url: https://github.com/minesa-org/mini-interaction/discussions
    about: For general questions or ideas, use Discussions instead of issues
